### ISSUE TITLE
Authentication problem on vagrant up

### ISSUE THREAD

**Issue by vaslabs** [couchbaselabs/vagrants#37]
Vagrant reports insecure key, tries to replace it and then it fails to connect back to the machine.

Vagrant version: 1.8.5
Host OS: Fedora 24, kernel 4.7.2-201.fc24.x86_64

Suggested fix:
https://github.com/vaslabs/vagrants/commit/384ec7e5b43f77a9d7a41473c07f052dbc9b3a25

**Comment by mcpaddy** [comment]
Hello @vaslabs, 

Thank you for reporting the problem and for the pull request. unfortunately I believe that this is an [known issue](https://github.com/mitchellh/vagrant/issues/7642) with vagrant 1.8.5 and not with our config. The issue is that vagrant 1.8.5 does not setup the new ssh keys correctly.

**Comment by vaslabs** [comment]
Yes, it's not a problem with your config, that's why I didn't do a pull request. Just in case people are looking for a temporary solution, until vagrant releases a fix.

**Comment by mcpaddy** [comment]
Vagrant 1.8.6 has been release which according to the [release notes](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#186-september-27-2016) fixes this issue. I have not had the  chance to verify it yet.

**Comment by mcpaddy** [comment]
Verified on Vagrant 1.8.6
