### ISSUE TITLE
OSX Yosemite 10.10.1 + VirtualBox 4.3.18 + Vagrant 1.6.5

### ISSUE THREAD

**Issue by davidchouse** [couchbaselabs/vagrants#9]
This may be a Vagrant / VirtualBox issue, but has anyone had success deploying on OSX Yosemite and VirtualBox 4.3.8? I am getting consistent network failures that lead to VM "aborts" using both CentOS6 and Ubuntu12. I have tried using a different box with updated Guest Additions, but get the same issue. 

Any advice is appreciated. Thanks!

**Comment by PaintScratcher** [comment]
Unsure if this will still be relevant, but for future reference the 'machine is in the
'aborted' state' error can arise in many situations. It's what happens when vagrant starts a VM and it fails for any reason. Running the int13 / ELDL=81 error gives a whole bunch of Google hits for various boot errors. 

Closing this for now as it isn't an issue with the repo. All the best.

**Comment by davidchouse** [comment]
It turns out that running "vagrant up" via sudo works fine. There must be a permission issue when creating the VMs. I installed vagrant via homebrew...not sure if that is the root cause.

**Comment by daverigby** [comment]
@davidchouse That sounds like some kind of issue with the Vagrant install - it works fine for me here (without sudo) - but I installed Vagrant via the download from it's own website...
